#%RAML 1.0 NamedExample
value:
  success: false
  appName: abc-app
  version: v1
  correlationId: 05c09130-75a2-11eb-9dcf-aed564bf8171
  timestamp: 1970-01-01T00:00:01.001-06:00
  errorDetails:
    code: 400
    reason: HTTP:BAD_REQUEST
    message: Error processing request
