#%RAML 1.0 NamedExample
value:
  - 
    ID: 100
    orderNumber: ORDER100ABC
    invoiceNumber: 100ABC
    createDate: 2020-11-10 13:44:12
    shipDate: 2020-11-10 13:44:12
    amount: 2500
  -
    ID: 200
    orderNumber: ORDER200ABC
    invoiceNumber: 200ABC
    createDate: 2020-11-10 13:44:12
    shipDate: 2020-11-10 13:44:12
    amount: 3500